Repository SSSD/sssd.io, pull requests merged in 2021-02, with the labels that each got.

#1 Add tests section
  src/contents.rst
  src/contrib/running-tests.rst
  src/contrib/tests/integration-tests.rst
  src/contrib/tests/multihost-tests.rst
  src/contrib/tests/unit-tests.rst
Labels: Accepted, Ready to push

#2 Add sudo troubleshooting guide
  src/troubleshooting/sudo.rst
Labels: Waiting for review

#7 Add Reporting Bugs page
  src/contents.rst
  src/docs/reporting-bugs.rst
Labels: Accepted
