Repository SSSD/sssd.io, pull requests merged in 2021-04, with the labels that each got.

#23 contrib: add talloc document
  src/contents.rst
  src/contrib/talloc.rst
Labels: Pushed

#21 Add cache req document
  src/contents.rst
  src/contrib/cache_req.rst
Labels: Waiting for review

#24 Add IPA Introduction
  src/docs/ipa/ipa-introduction.rst
Labels: Changes requested

#25 docs: AD Introduction
  src/docs/ad/ad-introduction.rst
Labels: Changes requested

#27 contrib: add tevent document
  src/contents.rst
  src/contrib/tevent.rst
Labels: Pushed, Waiting for review

#29 LDAP Introduction
  src/docs/ldap/ldap-introduction.rst
Labels: Pushed

#30 Add Krb5 introduction
  src/docs/krb/krb-introduction.rst
Labels: Waiting for review

#26 Adding quick start guide
  src/docs/quick-start.rst
Labels: Pushed

#31 introduction: polish the document
  src/docs/introduction.rst
Labels: Accepted
